name: Publish packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nakraniprakash'

      - run: npm install

      - name: Publish core
        run: npm publish
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish node
        run: npm publish
        working-directory: packages/node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish react
        run: npm publish
        working-directory: packages/react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
